[package]
name = "rust-ast-explorer"
version = "0.1.1"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[profile.release]
lto = true

[dependencies]
wasm-bindgen = "0.2.74"
syn = { version = "1.0.60", features = ["extra-traits", "full"] }
html-escape = "0.2.11"
